name: rmskin-build
description: packaging tool for Rainmeter User Content

inputs:
	version:  'auto'
		description: 'Version of the Rainmeter rmskin package.'
		required: false
	title: 'Unknown'
		description: 'Name of the Rainmeter rmskin package.'
		required: false
	author: 'Unknown'
		description: 'Account Username maintaining the rmskin package.'
		required: false
	path: '.'
		description: 'Base directory of repo being packaged.'
		required: false
outputs:
    arc_name: 
    description: 'path Filename of rmskin file'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.who-to-greet }}