name: rmskin-build
description: packaging tool for Rainmeter User Content

# for the badge
branding:
  icon: 'droplet'
  color: 'blue'

inputs:
  version:
    description: >-
      Version of the Rainmeter rmskin package.
      Defaults to last 8 digits of SHA from commit or reference tags.
    required: false
  title:
    description: >-
      Name of the Rainmeter rmskin package.
      Defaults name of repository.
    required: false
    default: ${{ github.event.repository.name }}
  author:
    description: >-
      Account Username maintaining the rmskin package.
      Defaults to Username that triggered the commit.
    required: false
    default: ${{ github.repository_owner }}
  path:
    description: >-
      Base directory of repo being packaged.
      Defaults to current working directory path.
    required: false
    default: "."
  dir_out:
    deprecationMessage: DEPRECATED. Use `dir-out` instead.
    description: >-
      Path to save generated rmskin package.
      Defaults to current working directory path.
    required: false
    default: "."
  dir-out:
    description: >-
      Path to save generated rmskin package.
      Defaults to current working directory path.
    required: false
    # default: "." # TODO: Uncomment when deprecated alias is removed

outputs:
  arc_name:
    # deprecationMessage: DEPRECATED. Use `arc-name` instead.
    description: The path to & name of the .rmskin file that was generated.
    value: ${{ steps.rmskin-builder.outputs.arc-name }}
  arc-name:
    description: The path to & name of the .rmskin file that was generated.
    value: ${{ steps.rmskin-builder.outputs.arc-name }}

runs:
    using: 'composite'
    steps:
    - name: Create temp bin directory
      # this path will be used to store the binaries outside of workspace root
      shell: bash
      run: mkdir "${GITHUB_ACTION_PATH%/}/bin"
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Install rmskin-builder binary
      shell: bash
      env:
        STANDALONE_BIN_VER: '2.0.0'
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        cargo-binstall -y
        rmskin-builder@${STANDALONE_BIN_VER}
        --install-path "${GITHUB_ACTION_PATH%/}/bin"
    - name: Run rmskin-builder
      shell: bash
      id: rmskin-builder
      run: >-
        ${GITHUB_ACTION_PATH%/}/bin/rmskin-build
        --path "${{ inputs.path }}"
        ${{ inputs.version && '--version ' || '' }}${{ inputs.version }}
        --author "${{ inputs.author }}"
        --title "${{ inputs.title }}"
        --dir_out "${{ inputs.dir-out || inputs.dir_out }}"
