name: rmskin-build
description: packaging tool for Rainmeter User Content

# for the badge
branding:
  icon: 'droplet'

inputs:
  version: # 'auto'
    description: "Version of the Rainmeter rmskin package. Defaults to last 8 digits of SHA from commit or reference tags."
    required: false
    default: 'auto'
  title: # 'repo-name'
    description: "Name of the Rainmeter rmskin package. Defaults name of repository."
    required: false
    default: ${{ github.event.repository.name }}
  author: # 'repo-owner'
    description: "Account Username maintaining the rmskin package. Defaults to Username that triggered the commit."
    required: false
    default:  ${{ github.repository_owner }}
  path: # '.'
    description: "Base directory of repo being packaged. Defaults to workflow's workspace path"
    required: false
    default: "/github/workspace"
  dir_out: # '.'
    description: "Path to save generated rmskin package. Defaults to workflow's workspace path"
    required: false
    default: "/github/workspace"

outputs:
  arc_name: # path to & name of archive file that was generated
    description: "name of rmskin file"

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.path }}
      - ${{ inputs.version }}
      - ${{ inputs.author }}
      - ${{ inputs.title }}
      - ${{ inputs.dir_out }}