version: "0.2"
words:
  - armv
  - autoupdate
  - binstall
  - bitness
  - bndy
  - caplog
  - cdylib
  - chrono
  - clippy
  - cookiecutter
  - Doherty
  - endfor
  - endgroup
  - endmacro
  - getattr
  - gnueabi
  - gnueabihf
  - hustcer
  - imageops
  - levelname
  - lfanew
  - manylinux
  - maturin
  - msvc
  - mypy
  - nextest
  - nurfile
  - nushell
  - orhun
  - pwsh
  - pyclass
  - pyfunction
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pyproject
  - pytest
  - Rainmeter
  - repr
  - rmskin
  - rustup
  - sccache
  - sdist
  - serde
  - testpypi
  - thiserror
  - timeit
  - topo
ignorePaths:
  - .gitattributes
  - .gitignore
