style = "conventional"
subject_capitalized = false
allowed_types = [
    "fix",
    "feat",
    "build",
    "chore",
    "docs",
    "style",
    "refactor",
    "remove",
    "deprecate",
    "security",
    "add",
    "perf",
    "test",
]
subject_length = 0 # unlimited
